### ISSUE TITLE
Lower rate data gets pulled

### ISSUE THREAD

**Issue by KennyGuldentops** [incama/Zabbix-Trigger-Web#1]
Hi there

I have deployed this board with success, however i have one more thing i'm struggling with.

When a trigger gets active it instantly appears on the board (after the reload time 30s). But when the trigger is deactivated it takes ~30 minutes for the trigger to disappear from the board.

Is there any way to decrease this number, and if so where can i do that? Or another way to bypass this 30 minute mark?

**Comment by incama** [comment]
What do you mean with "deactivated". Is it when  you acknowledge the event or when the issue resolves itselfs?
I have noticed the 30 minutes wait when acknowledging the trigger.

**Comment by KennyGuldentops** [comment]
I did find a solution. I changed the call.
Here is the code in servers-data.php so if other people want to use it they don't have to go trough the struggle

 // get hosts from groupid -------------------------------------------------$
    $events = $api->triggerGet(array(
                'output' => 'extend',
                'skipDependent' => 1,
                'selectTriggers' => 'extend',
                'selectGroups' => 'extend',
                'selectHosts' => 'extend',
                'filter' =>  ['value' => '1', 'status' => '0'],
                'withLastEventUnacknowledged' => 1,
                'expandDescription' => 1,
                'sortfield' => 'priority',
                'sortorder' => 'DESC',
                'groupids' => array('2','4','8','9'), // <-- PUT YOUR GROUPIDS

This will instantly update a trigger when it gets resolved.
Thanks for sharing this board!

**Comment by incama** [comment]
Nice way indeed. Will update the source. Thank a lot!
